### ISSUE TITLE
Vanilla apply results in error

### ISSUE THREAD

**Issue by dutchman80** [cloudposse/terraform-aws-lb-s3-bucket#49] opened 2022-03-07 20:54 UTC
Running a terraform apply (terraform v1.1.7) with the following resource definition results in the below error:

module "access_logs" {
  source                             = "cloudposse/lb-s3-bucket/aws"
  namespace                     = var.namespace
  name                               = var.name
}

╷
│ Error: Invalid count argument
│ 
│   on .terraform/modules/alb.access_logs/main.tf line 2, in data "aws_elb_service_account" "default":
│    2:   count = module.this.enabled ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the count depends on.
╵

**Comment by Nuru** [comment] 2023-05-06 07:16
Closing this as "invalid" because (a) I cannot reproduce the problem and (b) no module version was specified. Cloud Posse recommends always specifying a module version to avoid unexpected changes. 

If you can provide more information and reproduce this behavior with the current version of this module, please open a new issue.

**Closed by Nuru** 2023-05-06 07:16 UTC
Labels: invalid
